### ISSUE TITLE
Cannot create enough threads

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XLT-Packer#17]
In case an XLT load agent spawns a significant number of virtual users, we may observe the following error:
                                                                                                      
```
Exception in thread "main" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:803)
        at com.xceptance.xlt.agent.LoadTest.run(LoadTest.java:125)
        at com.xceptance.xlt.agent.Main.run(Main.java:247)
        at com.xceptance.xlt.agent.Main.main(Main.java:272)
```

Looks like we hit an OS limit and we now need to find out how to increase that limit for the cloud images we provide.

**Comment by jowerner** [comment]
These are the current thread limits on my cloud machine if XLT is run

* as a service: ~ 4,800 threads 
* by a regular user: ~ 10,700 threads  

Obviously the service limits are different from the user limits. When adding 

```
DefaultLimitNPROC=16000
DefaultTasksMax=16000
```

to `/etc/systemd/system.conf`, the XLT service was able to handle 15,000 virtual users without problems.

**Comment by h-arlt** [comment]
User limits are not effective when using SystemD unless it is run as user service (which is usually not the case).

However, instead of setting that high default values that apply to all units, I'd prefer to configure proper limits explicitly for unit `xlt.service`:
```
LimitNROC=16000
TasksMax=16000
```
